apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: authapp
        image: 211125685751.dkr.ecr.ap-northeast-2.amazonaws.com/woorizip-auth:20240508132118
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: service-auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort